# Generated by Django 5.0.6 on 2024-06-26 17:42

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='created_at',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='date_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='image',
            field=models.ImageField(blank=True, upload_to=users.models.user_directory_path),
        ),
    ]
