# Generated by Django 5.0.6 on 2024-07-31 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usermodel_email_verified_emailverificationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationmodel',
            name='code',
            field=models.CharField(max_length=128),
        ),
    ]
