# Generated by Django 5.0.6 on 2024-08-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_emailverificationmodel_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverificationmodel',
            options={'verbose_name': 'модель верификации', 'verbose_name_plural': 'верификации'},
        ),
        migrations.AddField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
