# Generated by Django 5.0.6 on 2024-07-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_tagmodel_itemmodel_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='slug',
            field=models.SlugField(default='test', max_length=128),
        ),
    ]
