# Generated by Django 5.0.6 on 2024-07-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_categorymodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='slug',
            field=models.SlugField(max_length=128, unique=True),
        ),
    ]
