# Generated by Django 5.0.6 on 2024-08-19 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_categorymodel_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basketmodel',
            options={'verbose_name': 'корзину', 'verbose_name_plural': 'корзины'},
        ),
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'verbose_name': 'категорию', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='itemmodel',
            options={'verbose_name': 'вещи', 'verbose_name_plural': 'вещи'},
        ),
        migrations.AlterModelOptions(
            name='tagmodel',
            options={'verbose_name': 'тег', 'verbose_name_plural': 'теги'},
        ),
    ]
