# Generated by Django 5.0.6 on 2024-08-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('processing', 'Подготовка заказа'), ('on_the_way', 'В пути'), ('delivered', 'Доставлен'), ('canceled', 'Отменен')], default='processing', max_length=10),
        ),
    ]
