# Generated by Django 5.0.6 on 2024-08-19 09:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordermodel_delivered_ordermodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='code',
            field=models.CharField(default=django.utils.timezone.now, max_length=7, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='items',
            field=models.JSONField(default=dict),
        ),
    ]
