# Generated by Django 5.0.6 on 2024-08-19 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_ordermodel_code_ordermodel_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='delivered',
            new_name='is_delivered',
        ),
    ]
